cfg = {
    "database": "data/alloy/alloy_AM2022",
    "continuous_feature_names": [
        "Maximum Stress",
        "Minimum Stress",
        "Frequency",
        "R-value",
        "fatigue temperature  (°C)",
        "ultimate tensile strength  (MPa)",
        "stress concentration factor of specimens",
        "critical cross-section size of specimens (mm)",
        "elongation  (%)",
        "Young's modulus  (GPa)",
        "yield strength  (MPa)",
        "direciton of specimen  (°)",
        "hatch space  (μm)",
        "layer scan rotation  (°)",
        "wire feed rate  (mm/s)",
        "scan speed  (mm/s)",
        "current  (A)",
        "preheat temperature  (°C)",
        "layer thickness  (μm)",
        "voltage  (V)",
        "powder feed rate  (g/s)",
        "power  (W)",
        "size of feedstock  (μm)",
        "speed function",
    ],
    "categorical_feature_names": [
        "load control",
        "types of feedstock",
        "fatigue environment",
        "types of AM",
        "AM environment",
        "scan pattern",
    ],
    "feature_types": {
        "Maximum Stress": "Fatigue loading",
        "Minimum Stress": "Fatigue loading",
        "Frequency": "Fatigue loading",
        "R-value": "Fatigue loading",
        "fatigue temperature  (°C)": "Fatigue loading",
        "ultimate tensile strength  (MPa)": "Material",
        "stress concentration factor of specimens": "Material",
        "critical cross-section size of specimens (mm)": "Material",
        "elongation  (%)": "Material",
        "Young's modulus  (GPa)": "Material",
        "yield strength  (MPa)": "Material",
        "direciton of specimen  (°)": "Material",
        "hatch space  (μm)": "Additive Manufacture",
        "layer scan rotation  (°)": "Additive Manufacture",
        "wire feed rate  (mm/s)": "Additive Manufacture",
        "scan speed  (mm/s)": "Additive Manufacture",
        "current  (A)": "Additive Manufacture",
        "preheat temperature  (°C)": "Additive Manufacture",
        "layer thickness  (μm)": "Additive Manufacture",
        "voltage  (V)": "Additive Manufacture",
        "powder feed rate  (g/s)": "Additive Manufacture",
        "power  (W)": "Additive Manufacture",
        "size of feedstock  (μm)": "Additive Manufacture",
        "speed function": "Additive Manufacture",
        "load control": "Fatigue loading",
        "types of feedstock": "Additive Manufacture",
        "fatigue environment": "Fatigue loading",
        "types of AM": "Additive Manufacture",
        "AM environment": "Additive Manufacture",
        "scan pattern": "Additive Manufacture",
    },
    "data_derivers": [
        [
            "SuppStressDeriver",
            {
                "derived_name": "Relative Maximum Stress",
                "stacked": True,
                "max_stress_col": "Maximum Stress",
                "min_stress_col": "Minimum Stress",
                "ucs_col": "ultimate tensile strength  (MPa)",  # UCS is not available in this dataset
                "uts_col": "ultimate tensile strength  (MPa)",
                "relative": True,
                "absolute": False,
            },
        ],
    ],
    "data_processors": [
        ["CategoricalOrdinalEncoder", {}],
        ["NaNFeatureRemover", {}],
        ["VarianceFeatureSelector", {"thres": 1}],
        ["StandardScaler", {}],
    ],
    "label_name": ["log10(Cycles to Failure)"],
}
