cfg = {
    "database": "alloy_AM2022",
    "feature_types": [
        "Fatigue loading",
        "Material",
        "Additive Manufacture",
        "Categorical",
        "Derived",
    ],
    "categorical_feature_names": [
        "load control",
        "types of feedstock",
        "fatigue environment",
        "types of AM",
        "AM environment",
        "scan pattern",
    ],
    "feature_names_type": {
        "Maximum Stress": 0,
        "Minimum Stress": 0,
        "Frequency": 0,
        "R-value": 0,
        "fatigue temperature  (°C)": 0,
        "ultimate tensile strength  (MPa)": 1,
        "stress concentration factor of specimens": 1,
        "critical cross-section size of specimens (mm)": 1,
        "elongation  (%)": 1,
        "Young's modulus  (GPa)": 1,
        "yield strength  (MPa)": 1,
        "direciton of specimen  (°)": 1,
        "hatch space  (μm)": 2,
        "layer scan rotation  (°)": 2,
        "wire feed rate  (mm/s)": 2,
        "scan speed  (mm/s)": 2,
        "current  (A)": 2,
        "preheat temperature  (°C)": 2,
        "layer thickness  (μm)": 2,
        "voltage  (V)": 2,
        "powder feed rate  (g/s)": 2,
        "power  (W)": 2,
        "size of feedstock  (μm)": 2,
        "speed function": 2,
        "load control": 3,
        "types of feedstock": 3,
        "fatigue environment": 3,
        "types of AM": 3,
        "AM environment": 3,
        "scan pattern": 3,
    },
    "data_derivers": [
        [
            "SuppStressDeriver",
            {
                "derived_name": "Relative Maximum Stress",
                "stacked": True,
                "max_stress_col": "Maximum Stress",
                "min_stress_col": "Minimum Stress",
                "ucs_col": "ultimate tensile strength  (MPa)",  # UCS is not available in this dataset
                "uts_col": "ultimate tensile strength  (MPa)",
                "relative": True,
                "absolute": False,
            },
        ],
    ],
    "data_processors": [
        ["CategoricalOrdinalEncoder", {}],
        ["NaNFeatureRemover", {}],
        ["VarianceFeatureSelector", {"thres": 1}],
        ["StandardScaler", {}],
    ],
    "label_name": ["log(Cycles to Failure)"],
}
