cfg = {
    "database": "composite_database_03222024",
    "continuous_feature_names": [
        "Fiber Volume Fraction",
        "Fiber Weight Fraction",
        "Fiber Weight Fraction (0-deg)",
        "Fiber Weight Fraction (45-deg)",
        "Fiber Weight Fraction (90-deg)",
        "Fiber Weight Fraction (Other Dir.)",
        "Thickness",
        "Tab Thickness",
        "Width",
        "Length",
        "Load Length",
        "Area",
        "Maximum Stress",
        "Minimum Stress",
        "Maximum Strain",
        "Minimum Strain",
        "R-value",
        "Frequency",
        "Ultimate Tensile Stress",
        "Ultimate Compressive Stress",
        "Tensile Modulus",
        "Compressive Modulus",
        "Ultimate Tensile Strain",
        "Ultimate Compressive Strain",
    ],
    "categorical_feature_names": ["Resin Type"],
    "feature_types": {
        "Resin Type": "Material",
        "Fiber Volume Fraction": "Material",
        "Fiber Weight Fraction": "Material",
        "Fiber Weight Fraction (0-deg)": "Material",
        "Fiber Weight Fraction (45-deg)": "Material",
        "Fiber Weight Fraction (90-deg)": "Material",
        "Fiber Weight Fraction (Other Dir.)": "Material",
        "Thickness": "Specimen",
        "Tab Thickness": "Specimen",
        "Width": "Specimen",
        "Length": "Specimen",
        "Load Length": "Specimen",
        "Area": "Specimen",
        "Maximum Stress": "Loading",
        "Minimum Stress": "Loading",
        "Maximum Strain": "Loading",
        "Minimum Strain": "Loading",
        "R-value": "Loading",
        "Frequency": "Loading",
        "Ultimate Tensile Stress": "Property",
        "Ultimate Compressive Stress": "Property",
        "Tensile Modulus": "Property",
        "Compressive Modulus": "Property",
        "Ultimate Tensile Strain": "Property",
        "Ultimate Compressive Strain": "Property",
    },
    "data_derivers": [
        [
            "MinStressDeriver",
            {
                "derived_name": "Minimum Stress",
                "stacked": True,
                "intermediate": True,
                "max_stress_col": "Maximum Stress",
                "r_value_col": "R-value",
            },
        ],
        # [
        #     "SuppStressDeriver",
        #     {
        #         "derived_name": "Support Stress",
        #         "stacked": True,
        #         "max_stress_col": "Maximum Stress",
        #         "min_stress_col": "Minimum Stress",
        #         "ucs_col": "Ultimate Compressive Stress",
        #         "uts_col": "Ultimate Tensile Stress",
        #         "relative": True,
        #         "absolute": False,
        #     },
        # ],
    ],
    "data_processors": [
        ["CategoricalOrdinalEncoder", {}],
        ["NaNFeatureRemover", {}],
        ["VarianceFeatureSelector", {"thres": 1}],
        ["StandardScaler", {}],
    ],
    "label_name": ["log10(Cycles to Failure)"],
}
