cfg = {
    "database": "composite_database_10082023_5mat",
    "continuous_feature_names": [
        "Fibre Volume Fraction",
        "Fibre Weight Fraction",
        "Fibre Weight Fraction (0-deg)",
        "Fibre Weight Fraction (45-deg)",
        "Fibre Weight Fraction (90-deg)",
        "Fibre Weight Fraction (Other Dir.)",
        "Thickness",
        "Tab Thickness",
        "Width",
        "Length",
        "Load Length",
        "Area",
        "Maximum Stress",
        "Minimum Stress",
        "Maximum Strain",
        "Minimum Strain",
        "R-value",
        "Frequency",
        "Ultimate Tensile Stress",
        "Ultimate Compressive Stress",
        "Tensile Modulus",
        "Compressive Modulus",
        "Ultimate Tensile Strain",
        "Ultimate Compressive Strain",
    ],
    "categorical_feature_names": ["Resin Type"],
    "feature_types": {
        "Resin Type": "Material/Specimen",
        "Fibre Volume Fraction": "Material/Specimen",
        "Fibre Weight Fraction": "Material/Specimen",
        "Fibre Weight Fraction (0-deg)": "Material/Specimen",
        "Fibre Weight Fraction (45-deg)": "Material/Specimen",
        "Fibre Weight Fraction (90-deg)": "Material/Specimen",
        "Fibre Weight Fraction (Other Dir.)": "Material/Specimen",
        "Thickness": "Material/Specimen",
        "Tab Thickness": "Material/Specimen",
        "Width": "Material/Specimen",
        "Length": "Material/Specimen",
        "Load Length": "Material/Specimen",
        "Area": "Material/Specimen",
        "Maximum Stress": "Fatigue loading",
        "Minimum Stress": "Fatigue loading",
        "Maximum Strain": "Fatigue loading",
        "Minimum Strain": "Fatigue loading",
        "R-value": "Fatigue loading",
        "Frequency": "Fatigue loading",
        "Ultimate Tensile Stress": "Material/Specimen",
        "Ultimate Compressive Stress": "Material/Specimen",
        "Tensile Modulus": "Material/Specimen",
        "Compressive Modulus": "Material/Specimen",
        "Ultimate Tensile Strain": "Material/Specimen",
        "Ultimate Compressive Strain": "Material/Specimen",
    },
    "data_derivers": [
        [
            "MinStressDeriver",
            {
                "derived_name": "Minimum Stress",
                "stacked": True,
                "intermediate": True,
                "max_stress_col": "Maximum Stress",
                "r_value_col": "R-value",
            },
        ],
        # [
        #     "WalkerStressDeriver",
        #     {
        #         "derived_name": "Walker Eq Stress",
        #         "stacked": True,
        #         "max_stress_col": "Maximum Stress",
        #         "r_value_col": "R-value",
        #         "power_index": 0.5,
        #     },
        # ],
        [
            "SuppStressDeriver",
            {
                "derived_name": "Support Stress",
                "stacked": True,
                "max_stress_col": "Maximum Stress",
                "min_stress_col": "Minimum Stress",
                "ucs_col": "Ultimate Compressive Stress",
                "uts_col": "Ultimate Tensile Stress",
                "relative": True,
                "absolute": False,
            },
        ],
        # [
        #     "DegLayerDeriver",
        #     {
        #         "sequence_column": "Sequence",
        #         "derived_name": "deg_layers",
        #         "col_names": [
        #             "0-deg layers",
        #             "45-deg layers",
        #             "90-deg layers",
        #             "Other-deg layers",
        #         ],
        #         "stacked": True,
        #     },
        # ],
        [
            "LayUpSequenceDeriver",
            {
                "sequence_column": "Sequence",
                "derived_name": "Lay-up Sequence",
                "stacked": False,
            },
        ],
        [
            "NumLayersDeriver",
            {
                "sequence_column": "Sequence",
                "derived_name": "Number of Layers",
                "stacked": False,
            },
        ],
        # ["SampleWeightDeriver", {"derived_name": "Sample Weight", "stacked": False}],
    ],
    "data_processors": [
        ["CategoricalOrdinalEncoder", {}],
        ["NaNFeatureRemover", {}],
        ["VarianceFeatureSelector", {"thres": 1}],
        ["StandardScaler", {}],
    ],
    "label_name": ["log10(Cycles to Failure)"],
}
