cfg = {
    "database": "alloy_CMA2022",
    "feature_types": [
        "Fatigue loading",
        "Material",
        "Categorical",
        "Derived",
    ],
    "categorical_feature_names": [
        "ingot shape",
        "atomic-level structure",
        "type of the material",
        "surface treatment",
        "load control",
        "fatigue environment",
    ],
    "feature_names_type": {
        "Frequency": 0,
        "R-value": 0,
        "fatigue temperature  (°C)": 0,
        "Maximum Stress": 0,
        "Minimum Stress": 0,
        "stress concentration factor of specimens": 1,
        "critical cross-section size of specimens (mm)": 1,
        "Young's modulus  (GPa)": 1,
        "grain size (μm)": 1,
        "ultimate tensile strength  (MPa)": 1,
        "elongation  (%)": 1,
        "glass transition temperature (°C)": 1,
        "yield strength  (MPa)": 1,
        "Ca": 1,
        "Zn": 1,
        "Mg": 1,
        "Zr": 1,
        "Cu": 1,
        "Al": 1,
        "Ni": 1,
        "Ti": 1,
        "Be": 1,
        "Nb": 1,
        "Ag": 1,
        "Co": 1,
        "Fe": 1,
        "B1": 1,
        "Si": 1,
        "B2": 1,
        "Sr": 1,
        "Pd": 1,
        "Er": 1,
        "Cr": 1,
        "Mn": 1,
        "C0": 1,
        "ingot shape": 2,
        "atomic-level structure": 2,
        "type of the material": 2,
        "surface treatment": 2,
        "load control": 2,
        "fatigue environment": 2,
    },
    "data_derivers": [
        [
            "SuppStressDeriver",
            {
                "derived_name": "Relative Maximum Stress",
                "stacked": True,
                "max_stress_col": "Maximum Stress",
                "min_stress_col": "Minimum Stress",
                "ucs_col": "ultimate tensile strength  (MPa)",  # UCS is not available in this dataset
                "uts_col": "ultimate tensile strength  (MPa)",
                "relative": True,
                "absolute": False,
            },
        ],
    ],
    "data_processors": [
        ["CategoricalOrdinalEncoder", {}],
        ["NaNFeatureRemover", {}],
        ["VarianceFeatureSelector", {"thres": 1}],
        ["StandardScaler", {}],
    ],
    "label_name": ["log(Cycles to Failure)"],
}
