cfg = {
    "database": "data/alloy/alloy_CMA2022_remove",
    "continuous_feature_names": [
        "Frequency",
        "R-value",
        "fatigue temperature  (°C)",
        "Maximum Stress",
        "Minimum Stress",
        "stress concentration factor of specimens",
        "critical cross-section size of specimens (mm)",
        "Young's modulus  (GPa)",
        "grain size (μm)",
        "ultimate tensile strength  (MPa)",
        "elongation  (%)",
        "glass transition temperature (°C)",
        "yield strength  (MPa)",
        "Ca",
        "Zn",
        "Mg",
        "Zr",
        "Cu",
        "Al",
        "Ni",
        "Ti",
        "Be",
        "Nb",
        "Ag",
        "Co",
        "Fe",
        "B1",
        "Si",
        "B2",
        "Sr",
        "Pd",
        "Er",
        "Cr",
        "Mn",
        "C0",
    ],
    "categorical_feature_names": [
        "ingot shape",
        "atomic-level structure",
        "type of the material",
        "surface treatment",
        "load control",
        "fatigue environment",
    ],
    "feature_types": {
        "Frequency": "Fatigue loading",
        "R-value": "Fatigue loading",
        "fatigue temperature  (°C)": "Fatigue loading",
        "Maximum Stress": "Fatigue loading",
        "Minimum Stress": "Fatigue loading",
        "stress concentration factor of specimens": "Material",
        "critical cross-section size of specimens (mm)": "Material",
        "Young's modulus  (GPa)": "Material",
        "grain size (μm)": "Material",
        "ultimate tensile strength  (MPa)": "Material",
        "elongation  (%)": "Material",
        "glass transition temperature (°C)": "Material",
        "yield strength  (MPa)": "Material",
        "Ca": "Material",
        "Zn": "Material",
        "Mg": "Material",
        "Zr": "Material",
        "Cu": "Material",
        "Al": "Material",
        "Ni": "Material",
        "Ti": "Material",
        "Be": "Material",
        "Nb": "Material",
        "Ag": "Material",
        "Co": "Material",
        "Fe": "Material",
        "B1": "Material",
        "Si": "Material",
        "B2": "Material",
        "Sr": "Material",
        "Pd": "Material",
        "Er": "Material",
        "Cr": "Material",
        "Mn": "Material",
        "C0": "Material",
        "ingot shape": "Material",
        "atomic-level structure": "Material",
        "type of the material": "Material",
        "surface treatment": "Material",
        "load control": "Fatigue loading",
        "fatigue environment": "Fatigue loading",
    },
    "data_derivers": [
        [
            "SuppStressDeriver",
            {
                "derived_name": "Relative Maximum Stress",
                "stacked": True,
                "max_stress_col": "Maximum Stress",
                "min_stress_col": "Minimum Stress",
                "ucs_col": "ultimate tensile strength  (MPa)",  # UCS is not available in this dataset
                "uts_col": "ultimate tensile strength  (MPa)",
                "relative": True,
                "absolute": False,
            },
        ],
    ],
    "data_processors": [
        ["CategoricalOrdinalEncoder", {}],
        ["NaNFeatureRemover", {}],
        ["VarianceFeatureSelector", {"thres": 1}],
        ["StandardScaler", {}],
    ],
    "label_name": ["log10(Cycles to Failure)"],
}
